version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: windex
      POSTGRES_USER: root
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d windex"]
      interval: 10s
      retries: 5

  backend:
    build: .
    volumes:
      - ./server:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: windex
      DB_USERNAME: root
      DB_PASSWORD: password

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./server:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  dbdata: